spring.application.name=rutasmartservice-master
server.port=8080

spring.datasource.url=jdbc:postgresql://db.pzfgkzdzseqielzmyrdh.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=RutaSmart2026*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true

supabase.url=https://pzfgkzdzseqielzmyrdh.supabase.co
supabase.anon-key=

app.frontend-url=


